### ISSUE TITLE
建议加个选项将读与写分开

### ISSUE THREAD

**Issue by chinaZoulx** [Zhou-zhi-peng/SerialPortForWindowsTerminal#1]
一般开一个窗口，串口数据太多，写时会将数据顶掉，挺麻烦的。
建议将读与写做可配置的。
这样可以实现一个读写看数据
一个窗口写数据，互不影响

**Comment by chinaZoulx** [comment]
用vs studio打开无法编译呢，你是用什么IED开发的？

**Comment by Zhou-zhi-peng** [comment]
这是一个串终端，用于做命令交互的，如果想一起保留输出数据，可以看看这个：
https://github.com/Zhou-zhi-peng/NetDebugger
这个可以专门针对串口调试，输入和输出分开的，而且有自动保存功能。

另外，这个项目是用VS2019编写的，依赖boost，其它没有什么特殊的，如果打不开项目，应该是VS版本太低了
