### ISSUE TITLE
执行mv命令的时候会出现光标跳到行首

### ISSUE THREAD

**Issue by you227** [Zhou-zhi-peng/SerialPortForWindowsTerminal#5]
执行mv命令的时候会出现光标跳到行首重新开始，但是不影响命令的执行。推测应该是命令行超长的原因
`localIntelligent_gardens-1.0-SNAPSHOT-jar-with-dependencies.jar`

1.
![image](https://user-images.githubusercontent.com/53899627/148358337-77236a09-09a9-426a-811d-7fd7a6f631bb.png)
2.
![image](https://user-images.githubusercontent.com/53899627/148358377-5130bdce-b9d6-4746-9d3e-a836956dda8f.png)
3.
![image](https://user-images.githubusercontent.com/53899627/148358463-1b85131b-8bac-42fc-9199-d13f2560f46a.png)

**Comment by Zhou-zhi-peng** [comment]
命令执行完成之后，会恢复正常吗？

**Comment by Zhou-zhi-peng** [comment]
理论上，这个程序只是为Window Terminal提供了串口通讯能力，终端字符渲染仍然由Window Terminal负责，如果字符渲染不正确，需要确认更新Window Terminal是否能解决？
另外，串口参数的错误也有可能导致字符位置不正确（主要是流控参数，通讯两端一定要一致，可以先尝试将流控改为软件流控）
我也去确认一下，是否有终端参数设置错误会导致字符渲染错误。

**Comment by Zhou-zhi-peng** [comment]
![image](https://user-images.githubusercontent.com/39650177/148362175-d7197953-29be-4fc7-9e30-1c25fde125c3.png)
此处先尝试将流控改为软件流控，看看问题是否解决？

**Comment by you227** [comment]
> 命令执行完成之后，会恢复正常吗？

执行完成后会恢复正常

**Comment by you227** [comment]
> 理论上，这个程序只是为Window Terminal提供了串口通讯能力，终端字符渲染仍然由Window Terminal负责，如果字符渲染不正确，需要确认更新Window Terminal是否能解决？ 另外，串口参数的错误也有可能导致字符位置不正确（主要是流控参数，通讯两端一定要一致，可以先尝试将流控改为软件流控） 我也去确认一下，是否有终端参数设置错误会导致字符渲染错误。

Window Terminal已经是最新版

流控模式改成软件流控也还是会出现这个问题

如下的两种方式都是每行有80个字符之后，光标就会跳入行首
```
root@npi:~# dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
root@npi:/home/java/intelligent_gardens# ddddddddddddddddddddddddddddddddddddddd
```

![image](https://user-images.githubusercontent.com/53899627/148473071-1a42dd1c-76fc-4418-85f0-464c99cc4369.png)

**Comment by you227** [comment]
试了下xshell也会有这种问题

**Comment by Zhou-zhi-peng** [comment]
那应该是目标系统的输出问题。
